import './style.css';
import { World3D } from './world3d.js';

const API=import.meta.env.VITE_API_BASE||'http://localhost:3000';
const WS=import.meta.env.VITE_WS_BASE||API.replace(/^http/,'ws');
const state={token:localStorage.getItem('necpra_token')||'',user:null,ws:null,zone:'lobby',selectedGame:null,match:null};
document.querySelector('#app').innerHTML='<div id="boot"><div class="logo">N</div><h1>NECPRA WORLD</h1><p>Building the hotel world…</p></div><main id="shell" class="hidden"><canvas id="world"></canvas><header class="topbar"><div class="brand"><b>NECPRA</b><span>WORLD</span></div><div class="zone-tabs"><button data-zone="lobby">Lobby</button><button data-zone="restaurant">Restaurant</button><button data-zone="gamehall">Game Hall</button></div><div class="wallet"><span id="coins">0</span> coins · <span id="xp">0</span> XP</div></header><aside class="panel left"><h2>NECPRA HOTEL</h2><div id="zoneTitle">Grand Lobby</div><div id="playerList"></div><div class="hint">WASD / arrows move · Shift run · drag mouse to look · wheel zoom · E wave</div></aside><aside class="panel right"><h2>GAME HALL</h2><div id="games"></div></aside><section class="chat panel"><div id="chatLog"></div><form id="chatForm"><input id="chatInput" maxlength="180" placeholder="Say something…"><button>Send</button></form></section><div class="interaction">Explore the hotel · meet guests · play at the tables</div><section id="gameOverlay" class="overlay hidden"></section></main><section id="auth" class="auth"><div class="auth-card"><div class="logo">N</div><h1>NECPRA WORLD</h1><p>A living multiplayer hotel. Meet people, explore, compete.</p><div class="tabs"><button id="loginTab" class="active">Login</button><button id="registerTab">Create account</button></div><form id="authForm"><input id="login" placeholder="Username or email" autocomplete="username"><input id="email" class="hidden" placeholder="Email" type="email" autocomplete="email"><div class="password-wrap"><input id="password" placeholder="Password" type="password" autocomplete="current-password"><button type="button" id="passwordToggle" class="password-toggle">Show</button></div><input id="username" class="hidden" placeholder="Username (3–20 characters)" autocomplete="nickname"><button class="primary">Enter World</button><div class="or">or continue with Google</div><div id="googleButton"></div><div id="authError" class="error"></div></form><small>Server-authoritative multiplayer · virtual points only</small></div></section>';
const $=id=>document.getElementById(id);let registerMode=false,world=null;
function toggleAuth(){$('loginTab').classList.toggle('active',!registerMode);$('registerTab').classList.toggle('active',registerMode);$('login').classList.toggle('hidden',registerMode);$('email').classList.toggle('hidden',!registerMode);$('username').classList.toggle('hidden',!registerMode);$('password').setAttribute('autocomplete',registerMode?'new-password':'current-password');$('authForm .primary').textContent=registerMode?'Create & Enter':'Enter World';}
$('loginTab').onclick=()=>{registerMode=false;toggleAuth();};$('registerTab').onclick=()=>{registerMode=true;toggleAuth();};$('passwordToggle').onclick=()=>{const i=$('password'),show=i.type==='password';i.type=show?'text':'password';$('passwordToggle').textContent=show?'Hide':'Show';};
$('authForm').onsubmit=async e=>{e.preventDefault();$('authError').textContent='';try{const body=registerMode?{username:$('username').value.trim(),email:$('email').value.trim(),password:$('password').value}:{login:$('login').value.trim(),password:$('password').value};const r=await fetch(API+'/api/auth/'+(registerMode?'register':'login'),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Authentication failed');state.token=j.token;state.user=j.user;localStorage.setItem('necpra_token',state.token);startWorld();}catch(e){$('authError').textContent=e.message||'Authentication failed';}};
window.onGoogleCredential=async credential=>{try{const r=await fetch(API+'/api/auth/google',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({credential})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Google sign-in failed');state.token=j.token;state.user=j.user;localStorage.setItem('necpra_token',state.token);startWorld();}catch(e){$('authError').textContent=e.message||'Google sign-in failed';}};
function setupGoogle(){const id=import.meta.env.VITE_GOOGLE_CLIENT_ID;if(!id||!window.google?.accounts?.id)return;window.google.accounts.id.initialize({client_id:id,callback:window.onGoogleCredential});window.google.accounts.id.renderButton($('googleButton'),{theme:'outline',size:'large',width:340,text:'continue_with',shape:'pill'});}setTimeout(setupGoogle,800);
function startWorld(){$('auth').classList.add('hidden');$('boot').classList.remove('hidden');$('coins').textContent=state.user?.coins??0;$('xp').textContent=state.user?.xp??0;if(!world)world=new World3D($('world'),{localId:()=>state.user?.id,onMove:p=>send('world.move',p),onEmote:e=>{send('world.emote',{e});world.emote(e);},onPlayersChanged:refreshPlayers});$('boot p').textContent='Entering the hotel…';setTimeout(()=>{$('boot').classList.add('hidden');$('shell').classList.remove('hidden');},350);connectWS();loadGames();updateZoneUI();}
function updateStats(){$('coins').textContent=state.user?.coins??0;$('xp').textContent=state.user?.xp??0;}function send(t,d={}){if(state.ws?.readyState===WebSocket.OPEN)state.ws.send(JSON.stringify({t,d}));}
function connectWS(){if(!state.token||state.ws?.readyState===WebSocket.OPEN)return;state.ws=new WebSocket(WS+'/ws?token='+encodeURIComponent(state.token));state.ws.onopen=()=>send('world.join',{zone:state.zone});state.ws.onclose=()=>{state.ws=null;setTimeout(()=>state.token&&connectWS(),2000);};state.ws.onmessage=e=>{try{const m=JSON.parse(e.data);handleWS(m.t,m.d);}catch{}};}
function handleWS(t,d){if(t==='hello'&&d?.user){state.user=d.user;updateStats();}if(t==='world.joined'){state.zone=d.zone;world?.setZone(d.zone,d.x,d.y,d.z);world?.setRemotePlayers(d.players||[]);updateZoneUI();}if(t==='world.enter')world?.addRemote(d);if(t==='world.leave')world?.removeRemote(d.id);if(t==='world.state')(d.p||[]).forEach(p=>{if(p.id!==state.user?.id)world?.updateRemote(p);});if(t==='world.correct')world?.correct(d);if(t==='chat.zone')addChat(d.from,d.text);if(t==='world.emote'){addChat('★ '+(d.id===state.user?.id?'You':'Player'),'performed '+d.e);if(d.id===state.user?.id)world?.emote(d.e);}if(t==='room.invited')addChat('INVITE','Room '+d.code+' from '+d.from);if(['game.match.joined','game.match.state','game.match.action','game.match.finished'].includes(t)){state.match=d;renderMatch();}if(t==='game.match.left'||t==='room.left'){state.match=null;$('gameOverlay').classList.add('hidden');}if(t==='room.joined'||t==='room.update')renderTubeRoom(d);if(t==='tube.prepare')showTubePhase('Get ready','prepare');if(t==='tube.observe')showTubePhase('Watch the cup','observe');if(t==='tube.shuffle')showTubePhase('Mixing… follow the movement','shuffle');if(t==='tube.select')showTubePhase('Make your choice','select');if(t==='tube.reveal')showTubeReveal(d);if(t==='tube.end')showTubeEnd(d);if(t==='tube.aborted')addChat('SERVER',d.reason||'Tube room ended');if(t==='error')addChat('SERVER',d?.message||'Server error');}
function addChat(from,text){const row=document.createElement('div'),b=document.createElement('b');b.textContent=from||'Player';row.appendChild(b);row.appendChild(document.createTextNode(' '+(text||'')));$('chatLog').appendChild(row);$('chatLog').scrollTop=$('chatLog').scrollHeight;}
$('chatForm').onsubmit=e=>{e.preventDefault();const text=$('chatInput').value.trim();if(text){send('chat.zone',{text});$('chatInput').value='';}};document.querySelectorAll('[data-zone]').forEach(b=>b.onclick=()=>{state.zone=b.dataset.zone;send('world.join',{zone:state.zone});updateZoneUI();});
function updateZoneUI(){const names={lobby:'Grand Lobby',restaurant:'Signature Restaurant',gamehall:'Game Hall'};$('zoneTitle').textContent=names[state.zone]||state.zone;document.querySelectorAll('[data-zone]').forEach(b=>b.classList.toggle('active',b.dataset.zone===state.zone));}
function refreshPlayers(remotes){const list=[...remotes.values()];$('playerList').innerHTML='<div class="player-count">'+list.length+' other player'+(list.length===1?'':'s')+'</div>'+(list.map(p=>'<div class="player">● '+escapeHtml(p.name||'Player')+'</div>').join('')||'<div class="muted">Explore the hotel — players appear here.</div>');}
function escapeHtml(s){const d=document.createElement('div');d.textContent=String(s);return d.innerHTML;}
async function loadGames(){try{const r=await fetch(API+'/api/games/catalog');const j=await r.json();$('games').innerHTML=(j.games||[]).map(g=>'<button class="game" data-game="'+escapeHtml(g.id)+'"><b>'+escapeHtml(g.name)+'</b><small>'+escapeHtml(g.players)+'</small></button>').join('');document.querySelectorAll('.game').forEach(b=>b.onclick=()=>gameMenu(b.dataset.game));}catch{$('games').innerHTML='<div class="muted">Game catalog unavailable</div>';}}
function gameMenu(gameId){state.selectedGame=gameId;$('gameOverlay').classList.remove('hidden');const tube=gameId==='tube';$('gameOverlay').innerHTML='<div class="game-card"><button class="close" id="closeGame">×</button><div class="eyebrow">GAME HALL</div><h2>'+escapeHtml(gameId.replaceAll('-',' ').toUpperCase())+'</h2><p>'+ (tube?'Create a live table. Watch the cup, follow the shuffle, then pick a tube.':'Create a server-authoritative multiplayer match.')+'</p><div class="game-actions"><button id="createMatch" class="primary">'+(tube?'Create Table':'Create Match')+'</button><button id="joinMatch">Join by Code</button></div></div>';$('closeGame').onclick=()=>$('gameOverlay').classList.add('hidden');$('createMatch').onclick=()=>tube?send('room.create',{private:false}):send('game.match.create',{gameId});$('joinMatch').onclick=()=>{const code=prompt('Enter room/match code');if(code)send(tube?'room.join':'game.match.join',{code:code.trim()});};}
function renderTubeRoom(d){$('gameOverlay').classList.remove('hidden');const members=d.members||[],me=members.find(x=>x.userId===state.user?.id);$('gameOverlay').innerHTML='<div class="game-card tube-card"><button class="close" id="leaveTube">×</button><div class="eyebrow">LIVE TABLE</div><h2>TUBE CHALLENGE</h2><div class="code">ROOM <b>'+escapeHtml(d.code||'—')+'</b></div><p>Round '+(d.round||0)+'/'+(d.totalRounds||5)+' · '+escapeHtml(d.phase||'lobby')+'</p><div class="scoreboard">'+members.map(p=>'<div><b>'+escapeHtml(p.username)+'</b><span>'+(p.score||0)+' pts</span></div>').join('')+'</div><div class="match-actions">'+((d.phase==='lobby'&&d.hostId===state.user?.id)?'<button id="tubeStart" class="primary">START</button>':'')+(d.phase==='select'&&!me?.spectator?'<button class="tube-pick" data-slot="0">TUBE 1</button><button class="tube-pick" data-slot="1">TUBE 2</button><button class="tube-pick" data-slot="2">TUBE 3</button><button class="tube-pick" data-slot="3">TUBE 4</button>':'')+'</div><div id="tubeVisual" class="tube-visual"><div class="cup"><span></span><span></span><span></span><span></span></div><strong>Waiting for the table…</strong></div><div class="hint">Server owns the hidden answer, shuffle and rewards.</div></div>';$('leaveTube').onclick=()=>send('room.leave');if($('tubeStart'))$('tubeStart').onclick=()=>send('room.start');document.querySelectorAll('.tube-pick').forEach(b=>b.onclick=()=>{send('room.pick',{slot:Number(b.dataset.slot)});b.disabled=true;});}
function showTubePhase(title,cls){const v=$('tubeVisual');if(!v)return;v.innerHTML='<div class="cup '+cls+'"><span></span><span></span><span></span><span></span></div><strong>'+title+'</strong>';}function showTubeReveal(d){showTubePhase('REVEAL · TUBE '+(Number(d.ballSlot)+1),'reveal');(d.results||[]).forEach(r=>addChat(r.username,r.correct?'✓ Correct guess!':'Missed the reveal.'));}function showTubeEnd(d){if(!d.standings)return;showTubePhase('TABLE COMPLETE · '+(d.standings[0]?.username||'Winner'),'finished');d.standings.forEach((p,i)=>addChat('RESULT',(i+1)+'. '+p.username+' — '+p.score+' points'));}
function renderMatch(){const m=state.match||{},players=m.players||m.game?.players||[];$('gameOverlay').classList.remove('hidden');$('gameOverlay').innerHTML='<div class="game-card"><button class="close" id="leaveMatch">×</button><div class="eyebrow">MULTIPLAYER MATCH</div><h2>'+escapeHtml((m.gameId||state.selectedGame||'MATCH').replaceAll('-',' ').toUpperCase())+'</h2><div class="code">CODE <b>'+escapeHtml(m.code||'—')+'</b></div><p>Status: '+escapeHtml(m.status||'waiting')+'</p><div class="scoreboard">'+players.map(p=>'<div><b>'+escapeHtml(p.username||p.u||'Player')+'</b><span>'+(p.score??0)+' pts</span></div>').join('')+'</div><div class="match-actions"><button id="ready">READY</button><button id="start" class="primary">START</button></div><div class="hint">The match server controls scoring and rewards.</div></div>';$('leaveMatch').onclick=()=>send('game.match.leave');$('ready').onclick=()=>send('game.match.ready');$('start').onclick=()=>send('game.match.start');}
if(state.token){fetch(API+'/api/auth/me',{headers:{authorization:'Bearer '+state.token}}).then(r=>r.ok?r.json():Promise.reject()).then(j=>{state.user=j.user;startWorld();}).catch(()=>{localStorage.removeItem('necpra_token');state.token='';$('boot').classList.add('hidden');});}else $('boot').classList.add('hidden');